### ISSUE TITLE
Dynamic Raster Source Support

### ISSUE THREAD

**Issue by kildareflare** [urbica/react-map-gl#247] opened 2019-08-28 22:16 UTC
**Describe the bug**
I have a source of type 'raster'.
When I change the source url the map does not update.
The only way to get the map to update is remove the Source component and add it in again with the new url.

Looking at the source of Source component I see that the source is only swapped if the id or type is changed.
```
  if (id !== prevId || source.type !== prevSource.type) {
      this._map.removeSource(prevId);
      this._map.addSource(id, source);
      return;
    }
```
However even if I toggle the id to force a source update the layers will not be updated as raster is not handle here:

```
  if (source.type === 'geojson' && prevSource.type === 'geojson') {
      this._updateGeoJSONSource(id, prevSource, source);
      return;
    }

    if (source.type === 'vector' && prevSource.type === 'vector') {
      this._updateVectorSource(id, prevSource, source);
    }
```

> Is this by design?
> Is this related to this PR?: https://github.com/mapbox/mapbox-gl-js/pull/8048

**To Reproduce**
1. Create a map with a raster source
2. Assign a url
3. the map renders appropriate raster tiles
3. Change the url
4. the map  does not update with new raster tiles

**Expected behavior**
When the url is changed for a raster source, the tiles should update.

**Comment by kildareflare** [comment] 2019-08-29 21:04
Awesome, thanks for the quick response @stepankuzmin, I'll test this shortly.

One more question though. Is there a reason why the source is not updated on url change?
E.g. it is only currently updated on change of id or type

```
    if (id !== prevId || source.type !== prevSource.type) {
      this._map.removeSource(prevId);
      this._map.addSource(id, source);
      return;
    }
```

But in my use case I need to change the URL when the user toggles on/off layers.
The MapBox Url I have has embedded in an array, which can change based on user selection. 

E.g. the show param in this URL will change

>https://gisserver:6443/arcgis/rest/services/myService/export?>bbox=100.5,-100.334,200,-200&token=TOKEN&layers=show:2,3&size=256,256&imageSR=38>57&bboxSR=3857&format=png&transparent=true&f=image&dpi=96

Currently I would have to force a reload by either toggling the id or type; it would be a lot nicer to simply change the URL.

Or is the a reason why this is not possible?

**Comment by stepankuzmin** [comment] 2019-08-30 11:05
@kildareflare could you please provide an example for this issue? I can't reproduce this.

**Comment by anatolysukhanov** [comment] 2019-09-11 11:54
Does https://github.com/urbica/react-map-gl/pull/251 have anything to do with this?

**Comment by stepankuzmin** [comment] 2019-09-11 12:13
This should be resolved by https://github.com/urbica/react-map-gl/commit/be3aa67b0f611b1a02c03990d296253587205e5e

Try upgrading to the latest `1.11.0` version and feel free to reopen this issue if it doesn't work.

**Closed by stepankuzmin** 2019-09-11 12:13 UTC
