### ISSUE TITLE
onViewportChange not triggered using NavigationControl 

### ISSUE THREAD

**Issue by charlietfl** [urbica/react-map-gl#234] opened 2019-07-07 12:56 UTC
**Describe the bug**
Using default map zoom controls not triggering viewport change event in parent `<MapGL>`

**To Reproduce**
1. Go to docs example https://urbica.github.io/react-map-gl/#/Controls/NavigationControl
2. Edit code block adding `onViewportChange={viewport=>console.log(JSON.stringify(viewport))}` to `<MapGL>` component
3. Open console, drag map center...see new viewport config in console
4. Change zoom using `+/-` in NavControl ... no output

**Expected behavior**
Would expect event to be triggered using NavigationControl but instead it only seems to affect the map-gl instance

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by jperals** [comment] 2019-08-26 07:26
I'd like to have this fixed too. @stepankuzmin Shall I submit a PR?

**Comment by stepankuzmin** [comment] 2019-08-26 08:05
Hey @jperals! It would be really great! PRs are welcome!

**Comment by jperals** [comment] 2019-08-26 15:12
It seems like the problem is that MapGL's `_onViewportChange` filters events that have an `originalEvent` property set, but it turns out that for certain interactions (among them, those coming from the NavigationControl) don't provide this property: https://github.com/mapbox/mapbox-gl-js/issues/6405

I worked around this by just checking that the event exists (or that it's truthy, to be more exact) instead of its properties: https://github.com/jperals/react-map-gl/commit/f6fd40ba7d027c3affe77251e26719b2db08e43c

So this is the _simplest_ solution I could come up with. Would it make more sense to check for _some_ other properties in the object instead? This doesn't _seem_ to have side effects for our use case and passes the tests (though I had to modify one of them as you can see), but of course I'm open to your feedback @stepankuzmin.

**Comment by stepankuzmin** [comment] 2019-08-26 15:49
Thanks for the research, @jperals!

Unfortunately we can't remove check for `originalEvent` because it is the only way to detect user-initiated events. The most concise way to fix this issue, IMO, is to add `originalEvent` to events initiated using `NavigationControl`.

I've created PR for this in `mapbox-gl-js` repo https://github.com/mapbox/mapbox-gl-js/pull/8693

**Comment by stepankuzmin** [comment] 2019-09-11 12:16
This should be fixed in the nest version of `mapbox-gl` since PR is merged https://github.com/mapbox/mapbox-gl-js/pull/8693

**Closed by stepankuzmin** 2019-09-11 12:16 UTC

**Comment by derwaldgeist** [comment] 2020-01-24 13:39
Just stumbled upon the same problem in the GeolocationControl (#276). Is there any update on when a new version will arrive that fixed this?
